name: Update stream1

on:
  schedule:
    # Runs at the start of every hour
    - cron: '0 * * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for pushing changes
      pull-requests: write
      statuses: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for proper commit history
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests urllib3
    
    - name: Run update script
      id: update
      env:
        M3U_SOURCE_URL: ${{ secrets.M3U_SOURCE_URL }}
      run: |
        if ! python update_stream1.py; then
          echo "::error::Failed to update playlist"
          exit 1
        fi
        
    - name: Check for changes
      id: git-check
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add stream1.m3u
        if ! git diff --quiet && ! git diff --staged --quiet; then
          echo "changes_detected=true" >> $GITHUB_OUTPUT
        else
          echo "No changes detected"
          echo "changes_detected=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push changes
      if: steps.git-check.outputs.changes_detected == 'true'
      run: |
        git commit -m "Update M3U playlist [skip ci]"
        git push
